name: golden_runner
description: Commands to test and update goldens in a Docker container
version: 0.0.1
homepage:

executables:
  goldens:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.3.1
  meta: ^1.8.0
  path: ^1.8.3

flutter:
