name: super_editor_docs
description: Documentation for Super Editor
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  static_shock:
    git:
      url: https://github.com/flutter-bounty-Hunters/static_shock
      path: packages/static_shock

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
