name: super_editor_quill
description: "Quill extensions for Super Editor"
version: 0.1.0-dev.9
homepage: https://github.com/superlistapp/super_editor
funding:
  - https://flutterbountyhunters.com
  - https://github.com/sponsors/matthew-carroll
topics:
  - quill
  - delta
  - rich-text-editor
  - document-editor
  - super-editor
screenshots:
  - description: "Demo of a Quill-style editor built with super_editor_quill."
    path: doc/pub/screenshots/quill-clone.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  super_editor: ^0.3.0-dev.13
  logging: ^1.3.0
  dart_quill_delta: ^9.4.1
  collection: ^1.18.0

  # For public testing tools
  matcher: ^0.12.16+1
  text_table: ^4.0.3

#dependency_overrides:
#  super_editor:
#    path: ../super_editor
#  super_text_layout:
#    path: ../super_text_layout
#  attributed_text:
#    path: ../attributed_text

dev_dependencies:
  # Note: some testing dependencies are listed as regular dependencies
  #       so we can export testing tools.
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
