name: attributed_text
description: Text with metadata spans for easy text editing and styling.
version: 0.3.2
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  characters: ^1.2.0
  collection: ^1.15.0
  logging: ^1.0.1
  meta: ^1.7.0
  test: ^1.19.4

dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.0.4
