name: attributed_text
description: Text with metadata spans for easy text editing and styling.
version: 0.4.3
homepage: https://github.com/superlistapp/super_editor
funding:
  - https://flutterbountyhunters.com
  - https://github.com/sponsors/matthew-carroll
topics:
  - rich-text
  - attributed-string
  - annotated-text
  - annotated-string
  - super-editor

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  characters: ^1.2.0
  collection: ^1.15.0
  logging: ^1.3.0
  meta: ^1.7.0
  test: ^1.19.4

dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.0.4
