name: super_editor_markdown
description: Markdown (de)serialization for super_editor documents.
version: 0.1.3
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  super_editor: ^0.2.2
  logging: ^1.0.1
  markdown: ^4.0.0

dev_dependencies:
  # TODO: upgrade lints to 2.0.1 when we release super_editor 0.2.1
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.11.0

flutter:
  # no Flutter configuration
