name: super_editor_markdown
description: Markdown (de)serialization for super_editor documents.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  super_editor:
    git:
      url: https://github.com/simpleclub-extended/super_editor
      path: super_editor
      ref: simpleclub-stable
  logging: ^1.0.1
  markdown: ^5.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.11.0

flutter:
# no Flutter configuration