name: super_text_layout
description: Configurable, composable, extensible text display for Flutter.
version: 0.1.15
homepage: https://github.com/superlistapp/super_editor
funding:
  - https://flutterbountyhunters.com
  - https://github.com/sponsors/matthew-carroll
topics:
  - rich-text
  - text-layout
  - text-decorations
  - super-editor
  - widget
screenshots:
  - description: "Custom text highlights."
    path: doc/pub/screenshots/text-highlights.png
  - description: "Paint selections and carets."
    path: doc/pub/screenshots/selection-and-caret.png
  - description: "Show widgets near the caret."
    path: doc/pub/screenshots/follow-the-caret.png
  - description: "Show multiple user selections at the same time."
    path: doc/pub/screenshots/multiple-user-selections.png

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text: ^0.4.0
  collection: ^1.18.0
  logging: ^1.3.0

  # For inspector
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  # Override to local mono-repo path so devs can test this repo
#  # against changes that they're making to other mono-repo packages
#  attributed_text:
#    path: ../attributed_text

dev_dependencies:
  flutter_lints: ^2.0.1
  golden_toolkit: ^0.15.0
  args: ^2.3.1
  meta: ^1.8.0
  golden_runner:
    path: ../golden_runner

flutter:
  # no Flutter configuration
