name: super_text_layout
description: Configurable, composable, extensible text display for Flutter.
version: 0.1.0
homepage: https://github.com/superlistapp/super_editor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text: ^0.1.1
  logging: ^1.0.1

dependency_overrides:
  # Override to local mono-repo path so devs can test this repo
  # against changes that they're making to other mono-repo packages
  attributed_text:
    path: ../attributed_text

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.11.0

flutter:
  # no Flutter configuration
