name: super_text_layout
description: Configurable, composable, extensible text display for Flutter.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  attributed_text:
    git:
      url: https://github.com/simpleclub-extended/super_editor
      path: attributed_text
      ref: simpleclub-stable
  logging: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.11.0

flutter:
  # no Flutter configuration
